import type { Theme } from "@/components/visuals/GoalVisual";
import type { Timeframe } from "@/lib/timeframe";

/** A pre-written goal a user can adopt as-is. Ported 1:1 from reference/groundwork.html's `IDEAS`. */
export interface Idea {
  id: string;
  tf: Timeframe;
  theme: Theme;
  cat: string;
  title: string;
  why: string;
  reward: string;
  ms: string[];
}

export const IDEAS: Idea[] = [
  {
    id: "cpr",
    tf: "day",
    theme: "tree",
    cat: "Meaningful",
    title: "Learn CPR and the choking response",
    why: "Most people freeze in an emergency. A few hours of practice means you won't.",
    reward: "A proper coffee and pastry somewhere you've never been",
    ms: [
      "Watch a certified CPR video course (or book a one-day first aid course)",
      "Practise compressions to a 100–120 bpm song",
      "Learn the choking response for adults and babies",
      "Teach it to one friend",
    ],
  },
  {
    id: "tyre",
    tf: "day",
    theme: "strength",
    cat: "Life skill",
    title: "Change a car tyre start to finish",
    why: "A roadside skill that saves you from waiting hours for help.",
    reward: "Your own tyre pressure gauge for the car",
    ms: [
      "Find the jack, spanner and spare",
      "Loosen the wheel nuts before jacking",
      "Swap the wheel and tighten in a star pattern",
      "Check the spare's pressure",
    ],
  },
  {
    id: "knots",
    tf: "day",
    theme: "shelf",
    cat: "Life skill",
    title: "Tie 5 useful knots from memory",
    why: "Bowline, clove hitch, taut-line, figure-8 and trucker's hitch cover almost every tie-down.",
    reward: "A paracord keychain you tie yourself, plus a cold drink",
    ms: ["Bowline", "Clove hitch", "Taut-line hitch", "Figure-8", "Trucker's hitch, then all five blindfolded"],
  },
  {
    id: "cube",
    tf: "day",
    theme: "building",
    cat: "Fun",
    title: "Solve a Rubik's cube",
    why: "Everyone assumes it's genius-level. It's a method you can learn in an afternoon.",
    reward: "A proper speed cube",
    ms: ["White cross", "First layer", "Second layer", "Yellow cross", "Solve it without the guide"],
  },
  {
    id: "dish",
    tf: "week",
    theme: "tree",
    cat: "Life skill",
    title: "Master one signature meal",
    why: "Having one dish you can cook for anyone, anytime, is quietly impressive.",
    reward: "A good chef's knife",
    ms: [
      "Pick the dish and a trusted recipe",
      "Cook it once and note what went wrong",
      "Cook it again without the recipe",
      "Host three people and cook it for them",
    ],
  },
  {
    id: "juggle",
    tf: "week",
    theme: "strength",
    cat: "Fun",
    title: "Juggle three balls for 30 catches",
    why: "Great for focus and coordination, and ten minutes a day is enough.",
    reward: "A fourth ball, and film yourself for proof",
    ms: ["One-ball arcs, eye height", "Two-ball exchange", "Three-ball flash", "10 catches in a row", "30 catches in a row"],
  },
  {
    id: "sasl",
    tf: "week",
    theme: "shelf",
    cat: "Meaningful",
    title: "Learn the SASL alphabet and 50 signs",
    why: "South African Sign Language is an official language that very few hearing people know.",
    reward: "Dinner out with someone you tell about it",
    ms: [
      "Fingerspell the alphabet",
      "Fingerspell your name and three friends' names",
      "25 everyday signs",
      "50 everyday signs",
      "Sign a short self-introduction",
    ],
  },
  {
    id: "ship",
    tf: "week",
    theme: "building",
    cat: "Career",
    title: "Build and ship a tiny tool in one week",
    why: "Finished and public beats perfect and private. It's also portfolio proof.",
    reward: "A domain name for your next idea",
    ms: [
      "Pick one small problem",
      "Working version by day 4",
      "Write a short README",
      "Publish it with a live link",
      "Share it with 5 people",
    ],
  },
  {
    id: "stars",
    tf: "week",
    theme: "mountain",
    cat: "Fun",
    title: "Find 5 constellations and a planet by eye",
    why: "The southern sky is one of the best in the world, and most people can't name a thing in it.",
    reward: "A night drive out of the city to see the Milky Way",
    ms: [
      "Find the Southern Cross and the Pointers",
      "Use them to find due south",
      "Orion",
      "Scorpius",
      "Spot a planet with a sky app to confirm",
    ],
  },
  {
    id: "sunset",
    tf: "week",
    theme: "tree",
    cat: "Meaningful",
    title: "A 7-day phone sunset",
    why: "No phone after 21:00 for a week. You'll notice the difference in your sleep and thinking.",
    reward: "A new book for the evenings",
    ms: ["Set up a charging spot outside the bedroom", "Days 1–3", "Days 4–5", "Days 6–7", "Write down what changed"],
  },
  {
    id: "typing",
    tf: "month",
    theme: "shelf",
    cat: "Career",
    title: "Touch type at 60+ words per minute",
    why: "You type all day. This pays off every single working hour for the rest of your life.",
    reward: "A mechanical keyboard",
    ms: ["Home row without looking", "30 wpm", "45 wpm", "60 wpm at 95% accuracy"],
  },
  {
    id: "lang",
    tf: "month",
    theme: "shelf",
    cat: "Meaningful",
    title: "Hold a 2-minute conversation in a South African language you don't speak yet",
    why: "People light up when you make the effort in their language.",
    reward: "A meal out where you order in that language",
    ms: [
      "Pick the language and a speaker to practise with",
      "Greetings and introductions",
      "100 everyday phrases",
      "First 30-second conversation",
      "A 2-minute conversation",
    ],
  },
  {
    id: "pullups",
    tf: "month",
    theme: "strength",
    cat: "Body",
    title: "Get to 5 strict pull-ups",
    why: "One of the best measures of real, usable strength.",
    reward: "New workout gear",
    ms: ["30-second dead hang", "Slow negatives, 3 sets", "First strict pull-up", "3 in a row", "5 in a row"],
  },
  {
    id: "song",
    tf: "month",
    theme: "tree",
    cat: "Fun",
    title: "Play one full song on guitar or piano",
    why: "One song you can actually play is worth more than a year of 'I want to learn'.",
    reward: "A lesson with a real teacher",
    ms: [
      "Pick a song with 3–4 chords",
      "Learn each chord cleanly",
      "Smooth chord changes",
      "Play it through slowly",
      "Record yourself playing it at full speed",
    ],
  },
  {
    id: "talk",
    tf: "month",
    theme: "mountain",
    cat: "Career",
    title: "Give a 5-minute talk without notes",
    why: "Speaking clearly in front of people opens more doors than almost any technical skill.",
    reward: "A sharp shirt for your next talk",
    ms: [
      "Pick a topic you know well",
      "Outline three points",
      "Rehearse out loud five times",
      "Record one practice run and watch it",
      "Give the talk to a real audience",
    ],
  },
  {
    id: "parkrun",
    tf: "quarter",
    theme: "strength",
    cat: "Body",
    title: "Run a parkrun 5 km without walking",
    why: "Free, every Saturday morning, and surprisingly social.",
    reward: "Proper running shoes fitted at a running store",
    ms: [
      "Register and print your barcode",
      "Walk your first parkrun",
      "Run 1 km without stopping",
      "Run 3 km without stopping",
      "Run the full 5 km",
    ],
  },
  {
    id: "chess",
    tf: "quarter",
    theme: "building",
    cat: "Fun",
    title: "Reach a 1200 rating on Lichess",
    why: "Strategy, patience and pattern recognition in one game.",
    reward: "A weighted wooden chess set",
    ms: ["Learn the opening principles", "Do 100 tactics puzzles", "Reach 1000", "Reach 1100", "Reach 1200"],
  },
  {
    id: "photo",
    tf: "quarter",
    theme: "tree",
    cat: "Fun",
    title: "Shoot a 12-photo series in manual mode",
    why: "Learning light and exposure changes how you see everything, including your design work.",
    reward: "Print and frame your best shot",
    ms: [
      "Learn aperture, shutter speed and ISO",
      "Shoot 100 photos in manual",
      "Pick a theme for the series",
      "Shoot the series",
      "Choose the final 12",
    ],
  },
  {
    id: "cert",
    tf: "quarter",
    theme: "building",
    cat: "Career",
    title: "Pass one recognised tech certification",
    why: "A cert that matches the tools you already use turns experience into proof.",
    reward: "A weekend away",
    ms: ["Pick the cert and book the exam date", "Finish the official learning path", "Score 80%+ on two practice exams", "Pass the exam"],
  },
  {
    id: "fund",
    tf: "quarter",
    theme: "jar",
    cat: "Meaningful",
    title: "Build a one-month emergency fund",
    why: "Having a buffer changes how you handle every surprise.",
    reward: "A small treat paid for with money outside the fund",
    ms: [
      "Work out one month of essential costs",
      "Open a separate savings pocket",
      "25% saved",
      "50% saved",
      "75% saved",
      "100% saved",
    ],
  },
  {
    id: "tugela",
    tf: "quarter",
    theme: "mountain",
    cat: "Adventure",
    title: "Hike to the top of Tugela Falls",
    why: "Chain ladders up the Drakensberg to the top of one of the tallest waterfalls on Earth.",
    reward: "A night in a mountain lodge after the hike",
    ms: [
      "A 10 km local hike",
      "A 15 km hike with real elevation",
      "Plan the Sentinel car park route with a friend",
      "Summit and climb the chain ladders",
    ],
  },
  {
    id: "scuba",
    tf: "year",
    theme: "mountain",
    cat: "Adventure",
    title: "Get Open Water scuba certified",
    why: "A whole world most people never see. Sodwana Bay is one of the best places to learn.",
    reward: "A dive trip once you're certified",
    ms: ["Swim 200 m comfortably", "Complete the theory", "Pool training sessions", "Four open-water dives", "Certified"],
  },
  {
    id: "half",
    tf: "year",
    theme: "strength",
    cat: "Body",
    title: "Finish a 21 km half marathon",
    why: "The step after parkrun. Crossing that line stays with you.",
    reward: "A sports massage and a framed race photo",
    ms: ["Run 5 km", "Run 10 km", "Enter a race", "Run 16 km in training", "Finish the half marathon"],
  },
  {
    id: "books",
    tf: "year",
    theme: "shelf",
    cat: "Meaningful",
    title: "Read 12 books",
    why: "One a month. A mix of fiction, biography and books that challenge you.",
    reward: "Every 3 books, a bookshop visit. At 12, a special edition of your favourite",
    ms: ["3 books", "6 books", "9 books", "12 books"],
  },
  {
    id: "provinces",
    tf: "year",
    theme: "mountain",
    cat: "Adventure",
    title: "Visit all 9 South African provinces",
    why: "Most South Africans have seen three or four. Few can say they've seen all nine.",
    reward: "A printed photo book of the journey",
    ms: ["3 provinces", "5 provinces", "7 provinces", "All 9 provinces"],
  },
  {
    id: "teach",
    tf: "year",
    theme: "tree",
    cat: "Meaningful",
    title: "Teach someone a skill you have, start to finish",
    why: "Teaching is the best test of whether you really know something, and it changes someone else's year too.",
    reward: "A celebration meal together when they can do it on their own",
    ms: ["Choose the person and the skill", "Plan the steps", "First lesson", "Halfway check-in", "They do it without your help"],
  },
];
